name: Tests

on:
  [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
        auto-update-conda: true

    - name: Run tests
      timeout-minutes: 60
      run: |
        jupyter kernel &
        conda install pytest
        pytest tests
        
